services:
  - type: web
    name: deliasportfolio-umbraco
    env: dotnet
    branch: develop
    rootDir: DeliasWebsite/DeliasWebsite.Web
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/DeliasWebsite.Web.dll
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
