name: Build and deploy ASP.Net Core app to Azure Web App - deliasportfolio

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required for actions/checkout

    steps:
      # Step 1: Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Step 3: Restore NuGet packages
      - name: Restore Dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Step 5: Publish the project
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      # Step 6: Login to Azure using OIDC
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB63FF396FF74055B3DB9FD248B0F431 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_40C4B765D4E2432396E821FF07236B67 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FAEEF6AFD2F04B4296135B333608CDA2 }}

      # Step 7: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'deliasportfolio'
          slot-name: 'Production'
          package: './publish'
