name: Build and Deploy ASP.NET Core App to Azure Web App

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./DeliasWebsite/DeliasWebsite.Web.csproj -c Release -o ./publish

      - name: Create ZIP Package
        run: zip -r publish.zip ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB63FF396FF74055B3DB9FD248B0F431 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_40C4B765D4E2432396E821FF07236B67 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FAEEF6AFD2F04B4296135B333608CDA2 }}

      - name: Deploy using ZIP Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'deliasportfolio'
          slot-name: 'Production'
          package: './publish.zip'
